ALTER TABLE Facture ADD COLUMN type VARCHAR(20) NOT NULL DEFAULT 'DEFINITIVE';
ALTER TABLE Facture ADD COLUMN statut VARCHAR(30) NOT NULL DEFAULT 'EMISE';
ALTER TABLE Facture ADD COLUMN datecreation DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE Facture ADD COLUMN totalttc NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE Facture ADD COLUMN motifannulation VARCHAR(255); 
