CREATE TABLE Clients(
idClient BIGSERIAL PRIMARY KEY,
RCCM CHAR(20) NOT NULL,
raisonsociale VARCHAR(100) NOT NULL,
adresse VARCHAR(255) NOT NULL,
ville VARCHAR(50) NOT NULL,
pays VARCHAR(50) NOT NULL,
telephone VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
nomcontact VARCHAR(50) NOT NULL,
NIF VARCHAR(20) NOT NULL
);

