spring.application.name=Gestion-facturation
spring.datasource.url=jdbc:postgresql://localhost:5432/facturation
spring.datasource.username=postgres
spring.datasource.password= Postgres2026!
spring.jpa.hibernate.ddl-auto=update